name: Torrent Download & Upload to Filemirage

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  torrent-upload:
    runs-on: ubuntu-latest
    env:
      PIXELDRAIN_API_KEY: '9'
      FILEMIRAGE_API_TOKEN: '9QQH-DGES-CWQZ-FXNV'
      FOLDER_PATH: 'downloaded_files'
      ZIP_NAME: 'downloaded_files.zip'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install jq curl zip -y
          npm install -g webtorrent-cli --ignore-scripts
          curl -o page.txt "https://equestria-eta.vercel.app/api/pages/dprjjMvC8fCF/raw"

      - name: Download torrent content with WebTorrent
        run: |
          mkdir -p "$FOLDER_PATH"

          while IFS= read -r link || [ -n "$link" ]; do
            link=$(echo "$link" | tr -d '\r')
            if [ -n "$link" ] && [[ ! "$link" =~ ^# ]]; then
              echo "Downloading via WebTorrent: $link"
              webtorrent download "$link" -o "$FOLDER_PATH"
            fi
          done < page.txt

      - name: Zip downloaded files
        run: |
          echo "Compressing $FOLDER_PATH into $ZIP_NAME..."
          zip -r "$ZIP_NAME" "$FOLDER_PATH"

      - name: Upload zip file to Filemirage
        run: |
          SERVER=$(curl -s https://filemirage.com/api/servers | jq -r '.data.server')
          UPLOAD_ID=$(curl -s https://filemirage.com/api/servers | jq -r '.data.upload_id')
          
          echo "Using server: $SERVER"
          echo "Upload ID: $UPLOAD_ID"
          echo "Uploading: $ZIP_NAME"
          
          RESPONSE=$(curl -s -H "Authorization: Bearer $FILEMIRAGE_API_TOKEN" \
            -F "file=@$ZIP_NAME;filename=$ZIP_NAME" \
            "$SERVER/upload.php")
          
          success=$(echo "$RESPONSE" | jq -r '.success')
          if [ "$success" != "true" ]; then
              echo "Failed to upload $ZIP_NAME: $(echo "$RESPONSE" | jq -r '.message')"
              exit 1
          else
              echo "Successfully uploaded: $ZIP_NAME"
          fi
